### ISSUE TITLE
SyntaxError: invalid syntax on basic usage

### ISSUE THREAD

**Issue by sandeeprenjith** [VigneshSP94/ppdns_stress#1]
Getting the below error while trying to use the tool to create stress.

```
╭─nd33p@trv-wl-srenjith /mnt/c/Users/srenjith/Dropbox/gits/ppdns_stress ‹master›
╰─$ python ppdnstress.py                                                                    1 ↵
Enter the number of queries you wanna send: 3000
Enter the DNS server to be stressed: 192.168.130.9
Traceback (most recent call last):
  File "ppdnstress.py", line 7, in <module>
    dns_server = input('Enter the DNS server to be stressed: ')
  File "<string>", line 1
    192.168.130.9
              ^
SyntaxError: invalid syntax

```

**Comment by sandeeprenjith** [comment]
╭─nd33p@trv-wl-srenjith /mnt/c/Users/srenjith/Dropbox/gits/ppdns_stress ‹master*›
╰─$ python -V
Python 2.7.15rc1

**Comment by sandeeprenjith** [comment]
Works on Python3

```
╭─nd33p@trv-wl-srenjith /mnt/c/Users/srenjith/Dropbox/gits/ppdns_stress ‹master*›
╰─$ python3 ppdnstress.py
Enter the number of queries you wanna send: 3000
Enter the DNS verver to be stressed: 192.163.130.9
 Sent 3000%
```

**Comment by vprabhakarana10** [comment]
This was written in python3 without thinking of backward compatibility, sadly.
